##################################################
################ General Settings ################
##################################################

general_settings:
  bot_token: ODgAAAAAAAAAAADkx.GBBBBI.V6CCCCCCCCCCCCCCCCCCCCCCCC9mfsU

builtin_settings:
  status_changer_settings:
    # PLAYING / STREAMING / LISTENING / WATCHING / CUSTOM_STATUS / COMPETING
    activity_messages:
      - "COMPETING;開發中...;5000"
      - "COMPETING;Developing...;5000"

  console_logger_settings:
    - guild_id: 858672865355890708
      channel_id: 1277193832378667040
      log_type: [ "command", "button", "modal" ]
      format: "[%cl_type%] %user_mention% `%cl_interaction_string%`"